name: Spellcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@e464ae97d348eb3beb0c5a6296dc4388ad4484d9 # v6
        with:
          config: .cspell.json
          files: |
            **/*.md
            **/*.py
            **/*.yml
            **/*.yaml
          incremental_files_only: false
          strict: true
