name: Spellcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
        with:
          config: .cspell.json
          files: |
            **/*.md
            **/*.py
            **/*.yml
            **/*.yaml
          incremental_files_only: false
          strict: true
